exclude: |
  (?x)^(
    (?:out|outputs)/|
    share/|
    tmp_attachments/|
    report_parts_.*|
    report_top10_.*|
    repo_.*|
    badges/coverage\.svg
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  # 先格式化（會把 ; 拆行、消掉大多 E701/E702）
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.10
        args: ["--line-length=100"]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
