repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types_or: [python]
        files: ^(src|tests|scripts|configs|docs)/|^pyproject\.toml$|^README\.md$

      - id: isort
        name: isort (black profile)
        entry: isort --profile black
        language: system
        types_or: [python]
        files: ^(src|tests|scripts|configs|docs)/|^pyproject\.toml$

      - id: ruff
        name: ruff (fix)
        entry: ruff check --fix --exit-non-zero-on-fix
        language: system
        types_or: [python]
        files: ^(src|tests|scripts)/

# 不設定 default_stages（舊寫法會有棄用警告）
# 依預設：於 pre-commit 階段執行；手動可跑 pre-commit run -a
