line-length = 120
target-version = "py310"

[lint]
select = ["E","F","I","UP"]
ignore = ["E501"]  # 先不擋行寬
exclude = [
  ".venv/**",
  ".archive/**",
  ".portfolio_hidden/**",
  "audit_bundle*/**",
  "reports/**",
  "src_lowcov/**",
  "tests/**",
  "src/torch/**",
  "src/transformers/**",
  "tools/**",
  "src/smart_mail_agent/**",  # ← 新增，避免 internal 樹影響 lint 綠燈
]

[lint.per-file-ignores]
"src/modules/__init__.py" = ["F403"]
"src/spam/__init__.py" = ["F403"]
