target-version = "py310"
line-length = 100
force-exclude = true
[lint]
select = ["E","F"]
ignore = ["E501"]
extend-exclude = [
  "examples/**",
  "modules/**",
  "scripts/**",
  "tools/**",
  "bin/**",
  "assets/**",
  "site/**",
  "data/**",
  "out/**",
  "init_db.py",
]
