[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
#!/usr/bin/env python3
# 檔案位置：pyproject.toml
# 模組用途：定義 black / isort / flake8 / mypy 統一規範

[tool.black]
target-version = ["py311"]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
  \.venv
| \.git
| data
| dist
| build
)/
'''

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["src", "tests", "scripts"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203","W503"]
exclude = [".venv","data","build","dist",".git"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = false
no_implicit_optional = true
strict_optional = false

[project.scripts]
sma = "cli.sma:main"

[project]
name = "smart-mail-agent"
version = "0.3.0"
requires-python = ">=3.10"
