[build-system]
requires = ["setuptools>=68","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "smart-mail-agent"
version = "0.3.1"
description = "AI + RPA 郵件自動處理展示專案（面試版）"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [{ name="YOU-JIE" }]
keywords = ["email","NLP","automation","RPA"]
dependencies = []

[tool.setuptools]
package-dir = {""="src"}
packages = ["utils","actions"]

[tool.black]
line-length = 120
target-version = ["py310"]
exclude = '''
(
  /(\.git|\.venv|dist|build|htmlcov|\.mypy_cache|\.pytest_cache)/
  | ^/logs/
  | ^/data/output/
  | ^/assets/fonts/
  | ^/backups/
)
'''

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = [".venv","dist","build","htmlcov",".mypy_cache",".pytest_cache","backups","logs","data/output","assets/fonts"]
