name: CI Enterprise
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -U -r requirements.txt || true; fi
          pip install -U ruff mypy pytest pytest-cov mkdocs mkdocs-material pip-audit bandit
      - name: Lint (ruff)
        run: ruff check .
      - name: Type check (mypy)
        run: mypy src || true
      - name: Unit tests (offline focus)
        run: |
          pytest -q tests -m "not online" --cov=src --cov-report=xml --cov-report=term-missing
      - name: Security (pip-audit)
        run: pip-audit -r requirements.txt || true
      - name: SAST (bandit)
        run: bandit -q -r src || true
      - name: Build docs
        if: hashFiles('mkdocs.yml') != ''
        run: mkdocs build -q
      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
