name: Nightly

on:
  schedule:
    - cron: '0 17 * * *'  # 每天 01:00 台灣時間左右
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr
      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run tests (OFFLINE)
        env:
          OFFLINE: "1"
          PYTHONPATH: "src"
        run: |
          pytest -q --maxfail=1 --disable-warnings
