name: Release
on:
push:
tags:
- "v*"
jobs:
build-publish:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
with:
python-version: "3.11"
- name: Build
run: |
python -m pip install -U pip build twine
python -m build
twine check dist/*
- name: Publish to PyPI
if: ${{ secrets.PYPI_TOKEN != '' }}
env:
TWINE_USERNAME: token
TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
run: python -m twine upload dist/*
