name: CI (offline)

on:
  pull_request:
  push:
    branches: [ main, diag-*, feature-* ]

jobs:
  test-offline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          pip install -U pytest black isort flake8
      - name: Lint (non-blocking)
        run: |
          python -m isort .
          python -m black --check .
          python -m flake8 || true
      - name: Run offline tests
        env:
          OFFLINE: "1"
        run: |
          PYTHONPATH=src pytest -q -k "not online"
