name: CI (offline)
on:
  push:
    branches: [ main, diag-* ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OFFLINE: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -U black isort flake8
          pip install -U black isort flake8
      - name: Run tests (exclude *online*)
        run: |
          pytest -q -k "not online"
