name: ci-offline

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10", cache: "pip" }
      - name: Install tools
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt pre-commit
      - name: Pre-commit (black/isort/flake8)
        run: pre-commit run --all-files --show-diff-on-failure

  e2e-offline:
    needs: lint
    runs-on: ubuntu-latest
    env:
      OFFLINE: "1"
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10", cache: "pip" }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run E2E tests (offline)
        run: |
          pytest -q tests/e2e --maxfail=1 --disable-warnings -q || EXIT=$?
          echo "pytest_exit=${EXIT:-0}" >> $GITHUB_OUTPUT
          exit ${EXIT:-0}
      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: |
            .pytest_cache
            ./**/out_*.json
            **/pytest*.xml
          if-no-files-found: ignore
