name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONUTF8: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      FORCE_COLOR: "1"
      OFFLINE: "1"   # 由程式/測試自行判斷離線路徑
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: System deps (fonts for PDF)
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Install deps
        run: |
          python -m pip install -U pip
          # project + dev
          python -m pip install -e .
          python -m pip install -U pytest pytest-cov ruff black isort pre-commit

      - name: Lint (ruff/black/isort)
        run: |
          ruff check .
          black --check .
          isort --profile black --check-only .

      - name: Run offline tests (unit + contracts; skip @online)
        run: |
          set -e
          targets=()
          for d in tests/unit tests/contracts; do
            [ -d "$d" ] && targets+=("$d")
          done
          if [ ${#targets[@]} -eq 0 ]; then
            echo "No unit/contracts dirs found; falling back to tests"
            targets=(tests)
          fi
          # 嘗試排除 @online；若無標記也能照常執行
          pytest -q --cov=src/smart_mail_agent --cov-report=term-missing --cov-report=xml \
                 -m "not online" "${targets[@]}" || {
            echo "Retry without marker filter (no @online markers?)"
            pytest -q --cov=src/smart_mail_agent --cov-report=term-missing --cov-report=xml \
                   "${targets[@]}"
          }

      - name: Upload coverage xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
