name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Install deps (minimal offline)
        run: |
          python -m pip install -U pip
          pip install -U pytest pytest-timeout pytest-cov "pydantic>=1,<3"
      - name: Run offline tests with coverage
        env:
          OFFLINE: "1"
          PYTHONPATH: "src"
        run: |
          pytest -q tests/unit tests/contracts -m "not online"             --cov=src/smart_mail_agent --cov-report=xml --cov-report=term-missing
      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
