name: CI
on:
  push: { branches: [ "main", "**" ] }
  pull_request:
concurrency: { group: ${{ github.workflow }}-${{ github.ref }}, cancel-in-progress: true }

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Install ruff
        run: |
          python -m pip install -U pip
          pip install ruff==0.6.4
      - name: Ruff (non-blocking)
        run: ruff check .
        continue-on-error: true

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e . || true
          pip install pytest
      - name: Offline pytest
        env:
          OFFLINE: "1"
          PYTHONWARNINGS: "ignore"
        run: |
          PYTHONPATH=".:src" pytest -q tests
