name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -U pytest pytest-cov coverage-badge
      - name: Run tests
        env:
          PYTHONPATH: .
          COV_UNDER: 95
        run: |
          pytest --cov-fail-under=$COV_UNDER
          coverage-badge -o assets/badges/coverage.svg -f
      - name: Upload badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: assets/badges/coverage.svg
