name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: System deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-osd poppler-utils
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e ".[ocr,llm,dev]"
      - name: Lint
        run: |
          ruff check --fix src tests_smoke
          black --check src tests_smoke
          isort --check-only src tests_smoke
      - name: Test
        run: pytest -q
