name: CI
on:
  push:
    branches: [ "main", "refactor/**", "chore/**" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 讓 workflow 可以把 coverage.svg 回推到 main
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov pytest-timeout genbadge[all]
      - name: Run offline tests with coverage
        env:
          OFFLINE: "1"
          PYTHONNOUSERSITE: "1"
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
          PYTHONPATH: ".:src"
        run: |
          pytest -q -p pytest_timeout -p pytest_cov \
            -m 'not online' \
            --cov --cov-branch \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage.xml \
            tests
      - name: Generate coverage badge
        run: |
          mkdir -p badges
          genbadge coverage -i coverage.xml -o badges/coverage.svg
      - name: Push badge back to main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add badges/coverage.svg
          git commit -m "ci: update coverage badge" || echo "no changes to commit"
          git push
