name: build
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

permissions:
  contents: read

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    env:
      PYTHONPATH: .:src
      OFFLINE: "1"

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -U pytest pytest-cov black isort ruff

      - name: Lint
        run: |
          ruff check src tests
          black --check src tests
          isort --check-only src tests

      - name: Tests
        run: |
          pytest -q --disable-warnings --cov=src --cov-report=xml --cov-report=term-missing
