name: CI
on:
  push:
    branches: [ "main", "**" ]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: 'requirements.txt'
      - run: python -m pip install -U pip ruff==0.6.4
      - name: Ruff (non-blocking)
      - name: Ruff format
        run: ruff format .
      - name: Ruff fix
        run: ruff check --fix .
        run: ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: 'requirements.txt'
      - name: Prepare runtime dirs
        run: mkdir -p data/output site reports
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt pytest pytest-cov
          pip install -e . || true
      - name: Offline pytest
        env:
          OFFLINE: "1"
          PYTHONWARNINGS: "ignore"
        run: |
          mkdir -p reports
          PYTHONPATH=".:src" pytest -q --cov=smart_mail_agent --cov-branch --cov-report=term-missing:skip-covered --cov-fail-under=60 tests | tee reports/coverage.txt
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: reports/coverage.txt
          if-no-files-found: error
          retention-days: 7
      - name: Coverage summary
        if: always()
        run: |
          echo '### Coverage summary' >> $GITHUB_STEP_SUMMARY
          tail -n +1 reports/coverage.txt >> $GITHUB_STEP_SUMMARY || true
