name: CI
on:
  push: { branches: [ "main", "**" ] }
  pull_request:
concurrency: { group: ${{ github.workflow }}-${{ github.ref }}, cancel-in-progress: true }
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10', cache: 'pip', cache-dependency-path: 'requirements.txt' }
      - run: python -m pip install -U pip ruff==0.6.4
      - run: ruff check .
        name: Ruff (non-blocking)
        continue-on-error: true
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10', cache: 'pip', cache-dependency-path: 'requirements.txt' }
      - name: Prepare runtime dirs
        run: mkdir -p data/output site reports
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -e . || true
      - name: Generate matrix (offline stub)
        env: { OFFLINE: "1" }
        run: python tools/run_actions_matrix.py
      - name: Offline pytest
        env:
          OFFLINE: "1"
          PYTHONWARNINGS: "ignore"
        run: PYTHONPATH=".:src" mkdir -p reports && PYTHONPATH=".:src" pytest -q --cov=smart_mail_agent --cov-branch --cov-report=term-missing:skip-covered tests | tee reports/coverage.txt
