name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -U -r requirements.txt || true; fi
          pip install -e .
          python -m pip install -U pytest pytest-cov pre-commit mkdocs mkdocs-material

      - name: Lint (pre-commit)
        run: |
          pre-commit run --all-files

      - name: Tests (offline subset)
        env:
          OFFLINE: "1"
          PYTHONPATH: "src"
        run: |
          pytest -q tests/unit tests/contracts -m "not online" \
            --cov=src/smart_mail_agent --cov-report=xml --cov-report=term-missing \
            --cov-fail-under=25

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Build docs
        run: mkdocs build -q
