name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U pytest pytest-timeout pre-commit ruff isort black

      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -v --cov=src/smart_mail_agent --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
