name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Lint (isort/black/flake8)
        run: |
          isort --check-only .
          black --check .
          flake8

      - name: Run tests (offline)
        env:
          OFFLINE: "1"
          PYTHONPATH: "src"
        run: |
          pytest -q

      - name: Demo run (bin/smarun)
        env:
          OFFLINE: "1"
          PYTHONPATH: "src"
        run: |
          chmod +x bin/smarun || true
          ./bin/smarun

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs-and-logs
          path: |
            data/output/out_*.json
            logs/sma-*.jsonl
          if-no-files-found: warn
