name: lint
on:
  push:
    branches: ['**']
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ruff (src)
        uses: astral-sh/ruff-action@v3
        with:
          version: latest
          args: check src

      - name: Ruff (tests, non-blocking)
        uses: astral-sh/ruff-action@v3
        continue-on-error: true
        with:
          version: latest
          args: check tests
