name: Lint
on:
  push: { branches: [ "**" ] }
  pull_request: { branches: [ "**" ] }
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Ruff
        run: |
          python -m pip install -U pip
          pip install ruff==0.12.9
      - name: Ruff check
        run: |
          ruff check --exclude 'examples/legacy_lowcov/**' .
      - name: Ruff format (dry-run)
        run: |
          ruff format --check --exclude 'examples/legacy_lowcov/**' .
