name: lint
on:
  push:
    branches: ['**']
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ruff
        run: python -m pip install --upgrade ruff

      - name: Ruff (src, strict)
        run: ruff check --force-exclude src

      - name: Ruff (tests, non-blocking)
        if: ${{ always() }}
        run: ruff check --force-exclude tests || true
