name: Lint (ruff)
on:
  push: { branches: [ "main", "chore/**", "refactor/**" ] }
  pull_request: { branches: [ "main" ] }
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - run: python -m pip install -U pip && pip install ruff
      - run: ruff check src
      - name: Ruff (tests, non-blocking)
        run: ruff check tests --exit-zero
- run: ruff format --check .
