name: offline-ci
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
jobs:
  offline-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install pytest only (offline-friendly)
        run: |
          python -m pip install -U pip
          python -m pip install pytest
      - name: Run offline tests
        env:
          OFFLINE: "1"
          PYTHONPATH: "src"
        run: |
          python -m pytest -q -k "not online"
