name: online-tests
on:
  workflow_dispatch:
  push: { branches: ['**'] }
jobs:
  online:
    if: ${{ github.event_name == 'workflow_dispatch' || (secrets.SMTP_USER != '' && secrets.SMTP_PASS != '') }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest
      - name: Run online/integration tests
        env:
          PYTHONPATH: .:src
        run: |
          if [ -d tests/online ] || [ -d tests/integration ]; then
            pytest -q tests/online tests/integration || true
          else
            echo "no online/integration tests present"
          fi
