name: Portfolio Tests
on:
  push:
    branches: [ "main", "cleanup/**" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install (editable with dev extras)
      run: |
        python -m pip install -U pip
        python -m pip install -e ".[dev]"
        python -m pip install -r requirements.txt || true
    - name: Lint (ruff + pre-commit)
      run: |
        python -m pip install pre-commit ruff
        ruff check .
        ruff format --check .
        pre-commit run --all-files || true
    - name: Run tests (offline only)
      env:
        PYTHONPATH: .
      run: |
        pytest -q tests -k "not online"
