name: release
on:
  push: { tags: [ 'v*' ] }
  workflow_dispatch:
permissions: { contents: read, packages: write }
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install isort black flake8 mypy
      - name: Lint & Type check & Test
        env: { PYTHONPATH: src, OFFLINE: "1" }
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
          isort .
          black .
          flake8 --config .flake8 .
          mypy --exclude '(^|/)(\.venv|data|build|dist)/' src || true
          pytest -q -k "not online"
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/smart-mail-agent
          tags: |
            type=ref,event=tag
            type=raw,value=latest
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
