name: security
on:
  pull_request:
  push:
    branches: [ "main", "develop" ]
jobs:
  sec-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install scanners
        run: |
          python -m pip install -U pip
          python -m pip install bandit detect-secrets
      - name: Bandit
        run: |
          bandit -q -r -x tests,data,.venv .
      - name: Detect Secrets
        run: |
          detect-secrets scan --all-files --exclude-files '.*(\.venv|\.git|data|artifacts|reports|archive).*' > ds_report.json
      - name: Upload detect-secrets report
        uses: actions/upload-artifact@v4
        with:
          name: detect-secrets
          path: ds_report.json
