name: tests
on: [push, pull_request]
permissions:
  contents: write
jobs:
  unit-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps (minimal)
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install "pytest>=7,<9" "coverage>=7,<8" \
                      python-dotenv PyYAML Jinja2 reportlab "pydantic>=2,<3" \
                      'genbadge[coverage]' coverage-badge
      - name: Run unit + contracts (no coverage)
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
          PYTHONPATH: ".:src"
          OFFLINE: "1"
          OMP_NUM_THREADS: "1"
          MKL_NUM_THREADS: "1"
          NUMEXPR_MAX_THREADS: "1"
        run: |
          . .venv/bin/activate
          pytest -q tests/unit tests/contracts
      - name: Coverage focus for modules/* and publish badge
        env:
          PYTHONPATH: ".:src"
          OFFLINE: "1"
        run: |
          . .venv/bin/activate
          coverage erase
          coverage run --branch --source=modules scripts/cov_focus_modules.py
          coverage xml -i --include="*/modules/*.py" -o coverage.xml
          mkdir -p badges
          genbadge coverage -i coverage.xml -o badges/coverage.svg || coverage-badge -o badges/coverage.svg -f
      - name: Commit coverage badge
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: update coverage badge [skip ci]"
          file_pattern: "badges/coverage.svg coverage.xml"
