name: tests
on: [push, pull_request]
permissions:
  contents: write
jobs:
  unit-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps (minimal)
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip coverage pytest python-dotenv PyYAML Jinja2 reportlab pydantic 'genbadge[coverage]' coverage-badge
      - name: Run unit + contracts
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
          PYTHONPATH: ".:src"
          OFFLINE: "1"
          OMP_NUM_THREADS: "1"
          MKL_NUM_THREADS: "1"
          NUMEXPR_MAX_THREADS: "1"
        run: |
          . .venv/bin/activate
          pytest -q tests/unit tests/contracts
      - name: Coverage focus + badge (quotation only)
        env:
          PYTHONPATH: ".:src"
          OFFLINE: "1"
        run: |
          . .venv/bin/activate
          coverage erase
          coverage run --branch --source=modules scripts/cov_focus_modules.py
          coverage xml -i --include="*/modules/quotation.py" -o coverage.xml
          mkdir -p badges
          (genbadge coverage -i coverage.xml -o badges/coverage.svg || coverage-badge -i coverage.xml -o badges/coverage.svg -f)
          echo "CI badge percent: $(grep -oE '[0-9]+(\\.[0-9]+)?%' badges/coverage.svg | head -1)"
      - name: Commit badge back to main
        if: github.ref == 'refs/heads/main'
        run: |
          . .venv/bin/activate
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add badges/coverage.svg coverage.xml
          git diff --cached --quiet || git commit -m "chore(ci): update coverage badge [skip ci]"
          git push
