name: tests (main, showcase & hardening)
on:
  push:
    branches:
      - "main"
      - "showcase/portfolio-clean-*"
      - "hardening/*"
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install (editable)
        run: |
          python -m pip install -U pip
          pip install -e . || pip install -r requirements.txt
      - name: Offline tests
        env:
          OFFLINE: "1"
          PYTHONPATH: ".:src"
          PRE_COMMIT_ALLOW_NO_CONFIG: "1"
        run: |
          pytest -q tests -k "not online" --timeout=60 --timeout-method=thread
