name: tests (portfolio-clean)
on:
  push:
    branches: [showcase/portfolio-clean-*]
  pull_request:
    branches: [showcase/portfolio-clean-*]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[dev]"
      - name: Offline tests only
        env:
          PYTHONPATH: .
        run: |
          pytest -q tests -k "not online" --timeout=60 --timeout-method=thread
