name: tests

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"  # 每天 UTC 20:00 跑 e2e

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: |
            requirements-unit.txt
            requirements-dev.txt
            requirements.txt
      - name: Install dependencies (lightweight)
        run: |
          python -m pip install -U pip
          if [ -f requirements-unit.txt ]; then
            pip install -r requirements-unit.txt
          elif [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          else
            pip install pytest pytest-timeout "pydantic>=1,<3"
          fi
      - name: Run unit/contracts
        run: pytest -q  # 受 pytest.ini 的 testpaths 限制

  e2e:
    if: github.event_name != 'pull_request'   # PR 不跑 e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install full dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run e2e
        run: pytest tests/e2e -m online -q
