name: tests (main, showcase & hardening)
on:
  push:
    branches:
      - "main"
      - "showcase/portfolio-clean-*"
      - "hardening/*"
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install (editable)
        run: |
          python -m pip install -U pip
          pip install -U pytest pytest-timeout pytest-cov
          pip install -e . || pip install -r requirements.txt
      - name: Offline tests + coverage
        env:
          OFFLINE: "1"
          PYTHONPATH: ".:src"
          PRE_COMMIT_ALLOW_NO_CONFIG: "1"
        run: |
          mkdir -p reports
          pytest -q tests -k "not online" --timeout=60 --timeout-method=thread \
            --cov=src --cov-report=term \
            --cov-report=xml:reports/coverage-offline.xml \
            --cov-report=html:reports/html-offline \
            --cov-fail-under=20
      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: reports/html-offline
      - name: Upload coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: reports/coverage-offline.xml
