name: tests

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"  # 每天 UTC 20:00 跑 e2e

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  unit:
    name: unit & contracts (fast)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - name: Install minimal deps
        run: |
          python -m pip install -U pip
          pip install -U pytest pytest-timeout "pydantic>=1,<3"
      - name: Run fast tests
        run: pytest -q   # pytest.ini 已限制 testpaths=tests/unit,tests/contracts

  e2e:
    name: e2e (online & heavy)
    if: github.event_name != 'pull_request'   # 避免 PR 時跑；push/main & schedule 會跑
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - name: Install full requirements
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run e2e (online)
        run: pytest tests/e2e -m online -q
