name: unit-and-coverage
on:
  push:
    branches: ['**']
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps (venv)
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest-timeout pytest-cov genbadge[coverage]
      - name: Run tests
        env:
          PYTHONPATH: .:src
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
        run: |
          . .venv/bin/activate
          pytest -q -k 'not online' -p pytest_cov --maxfail=1 \
            --cov=src --cov-branch \
            --cov-report=xml:coverage.xml \
            --cov-report=term-missing:skip-covered
      - name: Coverage badge
        run: |
          . .venv/bin/activate
          genbadge coverage -i coverage.xml -o badges/coverage.svg
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add badges/coverage.svg || true
          git commit -m "chore(badge): update coverage.svg [skip ci]" || echo "no changes"
          git push || true
      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
