name: tests
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"  # 每天 UTC 20:00 跑 e2e

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt
      - run: pytest -q  # 只收 tests/unit & tests/contracts（pytest.ini 已限制）

  e2e:
    if: github.event_name != 'pull_request'   # PR 不跑 e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt
      - run: pytest tests/e2e -m online -q
