name: tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  unit_contracts_fast:
    name: unit & contracts (fast)
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install (editable + dev + req files)
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[dev]"
          # 這兩行若檔案不存在不會失敗
          test -f requirements.txt && python -m pip install -r requirements.txt || true
          test -f requirements-dev.txt && python -m pip install -r requirements-dev.txt || true
          python -m pip list
      - name: Pytest (offline tests only)
        run: pytest -q tests -k "not online"
