name: tests (portfolio-clean)

on:
  push:
    branches:
      - "showcase/portfolio-clean-*"
  pull_request:
    branches:
      - "main"

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install (editable)
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[dev]"
      - name: Offline tests
        env:
          OFFLINE: "1"
          PYTHONPATH: src
        run: |
          pytest -q tests -k "not online" --timeout=60 --timeout-method=thread
