name: tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_contracts_fast:
    name: unit & contracts (fast)
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install (editable + dev)
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[dev]"
          # 額外保險：明確安裝 pydantic（v1 或 v2 都可，測試相容）
          python -m pip install "pydantic>=1.10,<3"
      - name: Run tests (offline)
        run: |
          pytest -q tests -k "not online" --timeout=60 --timeout-method=thread
