name: type
on:
  push:
    branches: ['**']
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install mypy + stubs
        run: |
          python -m pip install --upgrade pip
          pip install mypy types-PyYAML types-requests types-Pillow
      - name: Run mypy (non-blocking)
        continue-on-error: true
        run: mypy --config-file mypy.ini
