name: type
on:
  push:
    branches: ['**']
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install mypy & stubs
        run: |
          python -m pip install --upgrade pip
          pip install mypy types-PyYAML types-Jinja2
      - name: Run mypy
        env:
          MYPY_CACHE_DIR: .mypy_cache
        run: |
          mypy --install-types --non-interactive --python-version=3.10 src tests
