name: type
on:
  push:
    branches: ['**']
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install mypy & deps
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install -r requirements.txt || true

      - name: Run mypy (src & tests)
        run: |
          mypy --version
          mypy src tests --config-file mypy.ini --install-types --non-interactive
